import type { Config } from 'tailwindcss';

export default {
  content: ['./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '"Inter"',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        body: 'var(--body-font)',
        heading: 'var(--heading-font)',
      },
      colors: {
        body: 'var(--body)',
        'body-text': 'var(--text)',
        widget: 'var(--widget)',
        header: 'var(--header)',
        border: 'var(--border)',
        'input-border': 'var(--input-border)',
        'input-bg': 'var(--input-bg)',
        highlight: 'var(--highlight)',
        'highlight-inverse': 'var(--highlight-inverse)',
        accent: 'var(--accent)',
        red: 'var(--red)',
        green: 'var(--green)',
        'green-darker': '#02A189',
        orange: 'var(--orange)',
        yellow: 'var(--yellow)',
        gray: 'var(--gray)',
        'gray-red': 'var(--text-dark)',
        navy: {
          900: '#0A192F',
        },
      },
      screens: {
        '2xs': '375px',
        xs: '414px',
        '3xl': '1366px',
        '4xl': '1920px',
        '5xl': '2048px',
      },
      transitionDuration: {
        DEFAULT: '300ms',
      },
      borderColor: {
        DEFAULT: 'var(--border)',
      },
      boxShadow: {
        DEFAULT: 'var(--shadow)',
        banner: '0 2px 13px rgba(0, 54, 139, 0.44)',
        switch: 'inset 0 1px 3px rgba(170, 170, 183, 0.57)',
        'switch-dark': 'inset 0 1px 3px rgba(2, 2, 6, 0.57)',
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'pulse-fast': 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'ping-slow': 'ping 1.5s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
    },
  },
  safelist: [
    'text-center',
    'text-left',
    'text-right',
    'text-justify',
    'grid-cols-12',
    'grid-cols-11',
    'grid-cols-10',
    'grid-cols-9',
    'grid-cols-8',
    'grid-cols-7',
    'grid-cols-6',
    'grid-cols-5',
    'grid-cols-4',
    'grid-cols-3',
    'grid-cols-2',
    'grid-cols-1',
    'col-span-12',
    'col-span-11',
    'col-span-10',
    'col-span-9',
    'col-span-8',
    'col-span-7',
    'col-span-6',
    'col-span-5',
    'col-span-4',
    'col-span-3',
    'col-span-2',
    'col-span-1',
    'col-span-10',
    'col-span-9',
  ],
  important: true,
  plugins: [],
} satisfies Config;
